# Project
version=1.0.0
group=dev.purppecat.purps_mcu_reborn

# Mod options
mod_name=Purp's MCU: Reborn
mod_author=PurpPeCat
mod_id=purps_mcu_reborn
contributors=PurpPeCat
description=A Minecraft mod which immersively and interactively adds the MCU Universe into the minecraft realm.
license=LGPL-3.0
license_url=https://www.gnu.org/licenses/lgpl-3.0-standalone.html
icon=icon.png
github_name=Purps-MCU-Reborn
java_version=21

# Game versions
minecraft_version=1.21.1
next_minecraft_version=1.21.2
mdg_version=2.0.120
neoforge_version=21.1.235
major_fml_version=4

# Parchment
parchment_minecraft_version=1.21.1
parchment_version=2024.11.17

# Dependencies
tommylib_version=35.0.0
curios_version=9.5.1+1.21.1
geckolib_version=4.9.2
smartbrainlib_version=1.16.11

# Runtime
jade_version=15.10.5
jei_version=19.32.0.359

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
